name: Tag Armaria Extension

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push Tag
        run: ./scripts/tag.sh
